spring.datasource.url=jdbc:postgresql://localhost:5432/RoadDB
spring.datasource.username=YOUR_POSTGRES_USERNAME
spring.datasource.password=YOUR_POSTGRES_PASSWORD

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database-setup.sql
spring.jpa.defer-datasource-initialization=false

server.port=8081
